let string_to_operator s = match s with
	| "=" ->	EQUAL
	| ">" ->	GREATER
	| "<" ->	SMALLER
	| "!" ->	EXCLAMATION
	| "~" ->	TILDE
	| "?" ->	QUESTION
	| ";" ->	COLON
	| "==" ->	DOUBLEEQUAL
	| ">=" ->	GREATEROREQUAL
	| "<=" ->	SMALLEROREQUAL
	| "!=" ->	DIFFERENT
	| "&" ->	AND
	| "|" ->	OR
	| "&&" ->	DOUBLEAND
	| "||" ->	DOUBLEOR
	| "++" ->	INC
	| "--" ->	DEC
	| "+" ->	PLUS
	| "-" ->	MINUS
	| "*" ->	MUL
	| "/" ->	DIV
	| "^" ->	POWER
	| "%" ->	MOD
	| "+=" ->	PLUSEQUAL
	| "-=" ->	MINUSEQUAL
	| "*=" ->	MULEQUAL
	| "/=" ->	DIVEQUAL
	| "^=" ->	POWEREQUAL
	| "%=" ->	MODEQUAL
	| "<<" ->	DOUBLECHEVRONLEFT
	| "<<<" ->	TRIPLECHEVRONLEFT
	| ">>" ->	DOUBLECHEVRONRIGHT
	| ">>>" ->	TRIPLECHEVRONRIGHT
	| "<<=" ->	DOUBLECHEVRONLEFTEQUAL
	| "<<<=" ->	TRIPLECHEVRONLEFTEQUAL
	| ">>=" ->	DOUBLECHEVRONRIGHTEQUAL
	| ">>>=" ->	TRIPLECHEVRONRIGHTEQUAL
	| _ ->		NOTANOPERATOR
